# --- DAST PREP ---
      - name: Start Vulnerable App
        run: |
          docker compose up -d
          echo "Waiting for Juice Shop to start..."
          sleep 40 # Give it plenty of time to warm up

      # --- DAST STEP (StackHawk) ---
      - name: Run StackHawk Scan
        uses: stackhawk/hawkscan-action@v2
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          # No extra args needed now!
        env:
          APP_ID: "af84a5d9-0d41-4fa8-be44-79c41ae70ff8"
