name: DevSecOps Lab
on: [push] # Run every time we push code

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- SAST STEP (Trivy) ---
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'bkimminich/juice-shop:latest' # Scan the image for CVEs
          format: 'table'
          exit-code: '0' # We'll set to 0 for the lab so the pipeline doesn't stop
          severity: 'CRITICAL,HIGH'

      # --- DAST PREP ---
      - name: Start Vulnerable App
        run: docker compose up -d

      # --- DAST STEP (StackHawk) ---
      - name: Run StackHawk Scan
        uses: stackhawk/hawkscan-action@v2
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
        env:
          APP_ID: "af84a5d9-0d41-4fa8-be44-79c41ae70ff8" # Put your App ID here
